last_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "step" # name of the logged metric which determines when model is improving
  mode: "max" # "max" means higher metric value is better, can be also "min"
  save_top_k: -1 # save k best models (determined by above metric)
  save_last: True # additionally always save model from last epoch
  every_n_train_steps: 10000000000000000
  verbose: False
  dirpath: ${paths.output_dir}/checkpoints/
  filename: "{step:d}"
  auto_insert_metric_name: False
  save_weights_only: False
  save_on_train_epoch_end: True
